runtime: python39  # Specify the Python version
entrypoint: gunicorn -b :$PORT app:app  # Use Gunicorn to serve Flask

env_variables:
  GOOGLE_API_KEY: os.environ.get("GOOGLE_API_KEY") # Store your API key here

handlers:
- url: /static
  static_dir: static
- url: /.*  # This will route all other URLs to your app
  script: auto
